import { NextResponse } from "next/server";

export async function GET() {
  const grades = ["Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12"];

  const subjects = {
    "Grade 8": [
      "Mathematics",
      "English",
      "Life Orientation",
      "Creative Arts",
      "Social Sciences",
      "Technology",
      "Economics And Management Sciences"
    ],
    "Grade 9": [
      "Mathematics",
      "English",
      "Life Orientation",
      "Creative Arts",
      "Social Sciences",
      "Technology",
      "Economics And Management Sciences"

    ],
     "Grade 10": [
      "Accounting",
      "Agricultural Management Practices",
      "Agricultural Science",
      "Agricultural Technology",
      "Business Studies",
      "Civil Technology",
      "Computer Applications Technology",
      "Consumer Studies",
      "Dance Studies",
      "Design Studies",
      "Dramatic Arts",
      "Economics",
      "Electrical Technology",
      "Engineering Graphics and Design",
      "Equine Studies",
      "Geography",
      "History",
      "Hospitality Studies",
      "Information Technology",
      "Life Orientation",
      "Life Sciences",
      "Marine Sciences",
      "Maritime Economics",
      "Mathematical Literacy",
      "Mathematics",
      "Mechanical Technology",
      "Music",
      "Nautical Science",
      "Physical Sciences",
      "Religion Studies",
      "Sport and Exercise Science",
      "Technical Mathematics",
      "Technical Sciences",
      "Technical: Civil Technology",
      "Technical: Electrical Technology",
      "Technical: Mechanical Technology",
      "Tourism",
      "Visual Arts",
    ],
     "Grade 11": [
      "Accounting",
      "Agricultural Management Practices",
      "Agricultural Science",
      "Agricultural Technology",
      "Business Studies",
      "Civil Technology",
      "Computer Applications Technology",
      "Consumer Studies",
      "Dance Studies",
      "Design Studies",
      "Dramatic Arts",
      "Economics",
      "Electrical Technology",
      "Engineering Graphics and Design",
      "Equine Studies",
      "Geography",
      "History",
      "Hospitality Studies",
      "Information Technology",
      "Life Orientation",
      "Life Sciences",
      "Marine Sciences",
      "Maritime Economics",
      "Mathematical Literacy",
      "Mathematics",
      "Mechanical Technology",
      "Music",
      "Nautical Science",
      "Physical Sciences",
      "Religion Studies",
      "Sport and Exercise Science",
      "Technical Mathematics",
      "Technical Sciences",
      "Technical: Civil Technology",
      "Technical: Electrical Technology",
      "Technical: Mechanical Technology",
      "Tourism",
      "Visual Arts",
    ],
     "Grade 12": [
      "Accounting",
      "Agricultural Management Practices",
      "Agricultural Science",
      "Agricultural Technology",
      "Business Studies",
      "Civil Technology",
      "Computer Applications Technology",
      "Consumer Studies",
      "Dance Studies",
      "Design Studies",
      "Dramatic Arts",
      "Economics",
      "Electrical Technology",
      "Engineering Graphics and Design",
      "Equine Studies",
      "Geography",
      "History",
      "Hospitality Studies",
      "Information Technology",
      "Life Orientation",
      "Life Sciences",
      "Marine Sciences",
      "Maritime Economics",
      "Mathematical Literacy",
      "Mathematics",
      "Mechanical Technology",
      "Music",
      "Nautical Science",
      "Physical Sciences",
      "Religion Studies",
      "Sport and Exercise Science",
      "Technical Mathematics",
      "Technical Sciences",
      "Technical: Civil Technology",
      "Technical: Electrical Technology",
      "Technical: Mechanical Technology",
      "Tourism",
      "Visual Arts",
    ],
  };

  return NextResponse.json({ grades, subjects }, { status: 200 });
}
